[build]
engine_version = "277.0.0"
fork_id = "eclipse"

[game]
defaultpreset = "calm"

[infolinks]
discord = "https://discord.gg/zF8nQVy7Jf"
website = "https://eclipse-station.online"
wiki = "https://wiki.eclipse-station.online"
github = "https://github.com/ShalnayaKlyaksa/eclipse-server"
