using System.Linq;
using System.Numerics;
using Content.Client.MainMenu.UI;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly MarkingManager _marking = default!;

    private readonly SpriteSystem _sprite;
    private readonly BoxContainer _root;
    private readonly PanelContainer _leftPanel;
    private readonly PanelContainer _rightPanel;
    private readonly BoxContainer _zoneButtons;
    private readonly BoxContainer _filterButtons;
    private readonly BoxContainer _availableItems;
    private readonly BoxContainer _selectedItems;
    private readonly Label _selectedCount;
    private readonly LineEdit _searchBar;

    private MarkingsViewModel? _markingsModel;
    private BodyZone _selectedZone = BodyZone.Head;
    private MarkingFilter _selectedFilter = MarkingFilter.All;
    private bool _subscribed;
    // Set by ApplyResponsiveLayout and read while building rows, so the lists have to be rebuilt when they change.
    private bool _compactNav;
    private bool _compactEntries;

    // Left column (body zones + filters). It is the widest text in the picker, so it gives up the least.
    private const float LeftPanelWidth = 260f;
    private const float LeftPanelWidthCompact = 200f;
    private const float LeftPanelWidthVeryCompact = 156f;
    // Selected-markings column. Dropped entirely below RightPanelBreakpoint; markings can still be toggled off
    // from the available list, which shows them as selected.
    private const float RightPanelWidth = 470f;
    private const float RightPanelWidthCompact = 330f;
    private const float RightPanelShrinkBreakpoint = 1240f;
    private const float RightPanelBreakpoint = 980f;
    private const float VeryCompactBreakpoint = 720f;
    // Below this a full-size row leaves too little for the name (a 64px preview, the tag row and the +/OK column
    // eat ~140px), so rows drop their tags and shrink their preview to give the name back its width.
    private const float CompactEntryWidth = 420f;
    // Below this the zone/filter lists are too tall to scroll comfortably, so their buttons tighten up.
    private const float CompactNavHeight = 620f;
    private const float NavButtonHeight = 26f;
    private const float NavButtonHeightCompact = 22f;
    private const int NavSeparation = 6;
    private const int NavSeparationCompact = 3;
    private const int RootSeparation = 10;

    private static readonly Color PanelColor = Color.FromHex("#080706E8");
    private static readonly Color CardColor = Color.FromHex("#151311E8");
    private static readonly Color CardSelectedColor = Color.FromHex("#321A07F0");
    private static readonly Color BorderColor = Color.FromHex("#40230B");
    private static readonly Color AccentColor = Color.FromHex("#F08A12");
    private static readonly Color MutedTextColor = Color.FromHex("#B8B1A8");

    private static readonly ZoneDefinition[] Zones =
    [
        new(BodyZone.Head, "Голова", "☠", [HumanoidVisualLayers.Head, HumanoidVisualLayers.HeadTop, HumanoidVisualLayers.HeadSide, HumanoidVisualLayers.Snout, HumanoidVisualLayers.SnoutCover, HumanoidVisualLayers.Eyes]),
        new(BodyZone.Hair, "Волосы", "~", [HumanoidVisualLayers.Hair, HumanoidVisualLayers.FacialHair]),
        new(BodyZone.Torso, "Туловище", "▣", [HumanoidVisualLayers.Chest, HumanoidVisualLayers.Overlay, HumanoidVisualLayers.UndergarmentTop, HumanoidVisualLayers.UndergarmentBottom]),
        new(BodyZone.Tail, "Хвост", ">", [HumanoidVisualLayers.Tail, HumanoidVisualLayers.TailOverlay]),
        new(BodyZone.Arms, "Руки", "╎", [HumanoidVisualLayers.LArm, HumanoidVisualLayers.RArm, HumanoidVisualLayers.LHand, HumanoidVisualLayers.RHand]),
        new(BodyZone.Legs, "Ноги", "∥", [HumanoidVisualLayers.LLeg, HumanoidVisualLayers.RLeg]),
        new(BodyZone.Feet, "Стопы", "▔", [HumanoidVisualLayers.LFoot, HumanoidVisualLayers.RFoot]),
    ];

    private static readonly FilterDefinition[] Filters =
    [
        new(MarkingFilter.All, "Все"),
        new(MarkingFilter.Scars, "Шрамы"),
        new(MarkingFilter.Bandages, "Повязки"),
        new(MarkingFilter.Special, "Особые"),
        new(MarkingFilter.Face, "Лицо"),
        new(MarkingFilter.Eyes, "Глаза"),
        new(MarkingFilter.UpperEars, "Верхние уши"),
        new(MarkingFilter.LowerEars, "Нижние уши"),
        new(MarkingFilter.Horns, "Рога"),
    ];

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entity.System<SpriteSystem>();

        _root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = RootSeparation,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        AddChild(_root);
        LayoutContainer.SetAnchorPreset(_root, LayoutContainer.LayoutPreset.Wide);

        _leftPanel = CreatePanel(LeftPanelWidth);
        // The zone and filter lists are taller than the panel on small windows. Without a scroll container the
        // BoxContainer clamps the overflow to zero and stacks the last buttons on top of each other, which is what
        // made the bottom filters unclickable.
        var leftScroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HScrollEnabled = false,
            Margin = new Thickness(12),
        };
        _leftPanel.AddChild(leftScroll);
        var leftContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        leftScroll.AddChild(leftContent);
        _root.AddChild(_leftPanel);

        leftContent.AddChild(CreateHeader("Зоны тела"));
        _zoneButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        leftContent.AddChild(_zoneButtons);

        leftContent.AddChild(new Control { MinHeight = 12 });
        leftContent.AddChild(CreateDivider());
        leftContent.AddChild(CreateHeader("Фильтры"));
        _filterButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        leftContent.AddChild(_filterButtons);

        var middlePanel = CreatePanel(null);
        middlePanel.HorizontalExpand = true;
        middlePanel.VerticalExpand = true;
        var middleContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new Thickness(12),
        };
        middlePanel.AddChild(middleContent);
        _root.AddChild(middlePanel);

        middleContent.AddChild(CreateHeader("Доступные черты"));
        _searchBar = new LineEdit
        {
            PlaceHolder = Loc.GetString("markings-search"),
            HorizontalExpand = true,
        };
        _searchBar.OnTextChanged += _ => RebuildAvailableItems();
        middleContent.AddChild(_searchBar);

        var availableScroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        _availableItems = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        availableScroll.AddChild(_availableItems);
        middleContent.AddChild(availableScroll);

        _rightPanel = CreatePanel(RightPanelWidth);
        _rightPanel.VerticalExpand = true;
        var rightContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new Thickness(12),
        };
        _rightPanel.AddChild(rightContent);
        _root.AddChild(_rightPanel);

        var selectedHeader = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        selectedHeader.AddChild(CreateHeader("Выбрано"));
        selectedHeader.AddChild(new Control { HorizontalExpand = true });
        _selectedCount = new Label
        {
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactSubtle,
            VerticalAlignment = VAlignment.Center,
        };
        selectedHeader.AddChild(_selectedCount);
        rightContent.AddChild(selectedHeader);

        var selectedScroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        _selectedItems = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 10,
            HorizontalExpand = true,
        };
        selectedScroll.AddChild(_selectedItems);
        rightContent.AddChild(selectedScroll);

        var footer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        footer.AddChild(new Control { HorizontalExpand = true });
        var clear = new Button
        {
            Text = "Очистить",
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactButton,
            MinWidth = 150,
        };
        clear.OnPressed += _ => ClearSelectedZone();
        footer.AddChild(clear);
        rightContent.AddChild(footer);

        RebuildZoneButtons();
        RebuildFilterButtons();
        ApplyResponsiveLayout();
    }

    public void SetModel(MarkingsViewModel model)
    {
        if (_markingsModel == model)
            return;

        UnsubscribeModel();
        _markingsModel = model;
        SubscribeModel();
        RebuildAll();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        SubscribeModel();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        UnsubscribeModel();
    }

    protected override void Resized()
    {
        base.Resized();

        ApplyResponsiveLayout();
    }

    private void ApplyResponsiveLayout()
    {
        var compact = Width < RightPanelBreakpoint;
        var veryCompact = Width < VeryCompactBreakpoint;

        var leftWidth = veryCompact
            ? LeftPanelWidthVeryCompact
            : compact
                ? LeftPanelWidthCompact
                : LeftPanelWidth;
        var rightWidth = Width < RightPanelShrinkBreakpoint ? RightPanelWidthCompact : RightPanelWidth;
        var rightVisible = !compact;

        _leftPanel.SetWidth = leftWidth;
        _rightPanel.Visible = rightVisible;
        _rightPanel.SetWidth = rightWidth;

        // Whatever the middle column is left with once the side panels and the separations have taken their share.
        var middleWidth = Width - leftWidth - RootSeparation
                          - (rightVisible ? rightWidth + RootSeparation : 0f);

        var compactEntries = middleWidth < CompactEntryWidth;
        var compactNav = Height < CompactNavHeight;

        if (compactNav != _compactNav)
        {
            _compactNav = compactNav;
            RebuildZoneButtons();
            RebuildFilterButtons();
        }

        if (compactEntries != _compactEntries)
        {
            _compactEntries = compactEntries;
            RebuildAvailableItems();
            RebuildSelectedItems();
        }
    }

    private void SubscribeModel()
    {
        if (_markingsModel is null || _subscribed)
            return;

        _markingsModel.OrganDataChanged += RebuildAll;
        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += RebuildAll;
        _markingsModel.MarkingsReset += RebuildAll;
        _markingsModel.MarkingsChanged += OnMarkingsChanged;
        _subscribed = true;
    }

    private void UnsubscribeModel()
    {
        if (_markingsModel is null || !_subscribed)
            return;

        _markingsModel.OrganDataChanged -= RebuildAll;
        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= RebuildAll;
        _markingsModel.MarkingsReset -= RebuildAll;
        _markingsModel.MarkingsChanged -= OnMarkingsChanged;
        _subscribed = false;
    }

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            RebuildAll();
    }

    private void OnMarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (!CurrentZone.Layers.Contains(layer))
            return;

        RebuildAvailableItems();
        RebuildSelectedItems();
    }

    private void RebuildAll()
    {
        RebuildZoneButtons();
        RebuildFilterButtons();
        RebuildAvailableItems();
        RebuildSelectedItems();
    }

    private void RebuildZoneButtons()
    {
        _zoneButtons.RemoveAllChildren();
        _zoneButtons.SeparationOverride = _compactNav ? NavSeparationCompact : NavSeparation;

        foreach (var zone in Zones)
        {
            var selected = zone.Zone == _selectedZone;
            var button = new Button
            {
                Text = selected
                    ? $"▶  {zone.Icon}  {zone.Label}"
                    : $"   {zone.Icon}  {zone.Label}",
                HorizontalExpand = true,
                MinHeight = _compactNav ? NavButtonHeightCompact : NavButtonHeight,
                TextAlign = Label.AlignMode.Left,
                StyleIdentifier = selected ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierSecondary,
                ClipText = true,
            };
            button.OnPressed += _ =>
            {
                _selectedZone = zone.Zone;
                if (_selectedZone != BodyZone.Head && IsHeadOnlyFilter(_selectedFilter))
                    _selectedFilter = MarkingFilter.All;
                RebuildAll();
            };
            _zoneButtons.AddChild(button);
        }
    }

    private void RebuildFilterButtons()
    {
        _filterButtons.RemoveAllChildren();
        _filterButtons.SeparationOverride = _compactNav ? NavSeparationCompact : NavSeparation;

        foreach (var filter in Filters)
        {
            if (_selectedZone != BodyZone.Head && IsHeadOnlyFilter(filter.Filter))
                continue;

            var selected = filter.Filter == _selectedFilter;
            var button = new Button
            {
                Text = selected ? $"▶  {filter.Label}" : $"   {filter.Label}",
                HorizontalExpand = true,
                MinHeight = _compactNav ? NavButtonHeightCompact : NavButtonHeight,
                TextAlign = Label.AlignMode.Left,
                StyleIdentifier = selected ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierSecondary,
                ClipText = true,
            };
            button.OnPressed += _ =>
            {
                _selectedFilter = filter.Filter;
                RebuildFilterButtons();
                RebuildAvailableItems();
                RebuildSelectedItems();
            };
            _filterButtons.AddChild(button);
        }
    }

    private void RebuildAvailableItems()
    {
        _availableItems.RemoveAllChildren();

        if (_markingsModel is null)
            return;

        var query = _searchBar.Text.Trim();
        var entries = GetAvailableEntries()
            .Where(MatchesFilter)
            .Where(entry => MatchesSearch(entry.Prototype, query))
            .OrderBy(entry => GetMarkingName(entry.Prototype), StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        if (entries.Count == 0)
        {
            _availableItems.AddChild(CreateEmptyLabel("Нет доступных черт для выбранной зоны."));
            return;
        }

        foreach (var entry in entries)
        {
            _availableItems.AddChild(CreateAvailableEntry(entry));
        }
    }

    private void RebuildSelectedItems()
    {
        _selectedItems.RemoveAllChildren();

        if (_markingsModel is null)
        {
            _selectedCount.Text = "Выбрано: 0";
            return;
        }

        var selected = GetSelectedEntries().Where(MatchesFilter).ToList();
        _selectedCount.Text = $"Выбрано: {selected.Count}";

        if (selected.Count == 0)
        {
            _selectedItems.AddChild(CreateEmptyLabel("Выберите черту из списка слева."));
            return;
        }

        foreach (var group in selected.GroupBy(entry => GetLayerName(entry.Layer)).OrderBy(group => group.Key))
        {
            var groupHeader = new Label
            {
                Text = "▾ " + group.Key.ToUpperInvariant(),
                StyleIdentifier = MainMenuControl.StyleIdentifierCompactHeaderGold,
                Margin = new Thickness(0, 8, 0, 0),
            };
            _selectedItems.AddChild(groupHeader);

            foreach (var entry in group)
            {
                _selectedItems.AddChild(CreateSelectedEntry(entry));
            }
        }
    }

    private Control CreateAvailableEntry(MarkingEntry entry)
    {
        var selected = _markingsModel?.IsMarkingSelected(entry.Organ, entry.Layer, entry.Prototype.ID) == true;
        var panel = new Button
        {
            HorizontalExpand = true,
            StyleIdentifier = selected ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierSecondary,
        };
        panel.MinHeight = _compactEntries ? 56 : 84;
        panel.OnPressed += _ => ToggleMarking(entry, selected);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = _compactEntries ? 6 : 10,
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new Thickness(_compactEntries ? 5 : 8),
        };
        panel.AddChild(row);

        row.AddChild(CreatePreview(entry.Prototype, _compactEntries ? 40 : 64));

        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalAlignment = VAlignment.Center,
            HorizontalExpand = true,
        };
        var name = new Label
        {
            Text = GetMarkingName(entry.Prototype),
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactText,
            ClipText = true,
        };
        textColumn.AddChild(name);

        // The tag row cannot clip (its labels size themselves), so on a narrow column it is dropped rather than
        // pushing the name out of view. The same information is in the zone and filter selection anyway.
        if (!_compactEntries)
        {
            var tags = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                Margin = new Thickness(0, 6, 0, 0),
            };
            tags.AddChild(CreateTag(GetFilterLabel(entry.Prototype)));
            tags.AddChild(CreateTag(GetLayerName(entry.Layer)));
            foreach (var species in GetSpeciesTags(entry.Prototype))
            {
                tags.AddChild(CreateTag(species));
            }
            textColumn.AddChild(tags);
        }

        row.AddChild(textColumn);

        row.AddChild(new Label
        {
            Text = selected ? "OK" : "+",
            MinWidth = _compactEntries ? 26 : 48,
            VerticalAlignment = VAlignment.Center,
            StyleIdentifier = selected ? MainMenuControl.StyleIdentifierPrimary : MainMenuControl.StyleIdentifierCompactButton,
        });

        return panel;
    }

    private void ToggleMarking(MarkingEntry entry, bool selected)
    {
        if (_markingsModel is null)
            return;

        if (selected)
            _markingsModel.TryDeselectMarking(entry.Organ, entry.Layer, entry.Prototype.ID);
        else
            _markingsModel.TrySelectMarking(entry.Organ, entry.Layer, entry.Prototype.ID);
    }

    private Control CreateSelectedEntry(MarkingEntry entry)
    {
        var panel = CreateCard(false);
        panel.MinHeight = _compactEntries ? 48 : 64;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = _compactEntries ? 6 : 10,
            HorizontalExpand = true,
            Margin = new Thickness(_compactEntries ? 5 : 8),
        };
        panel.AddChild(row);

        row.AddChild(CreatePreview(entry.Prototype, _compactEntries ? 34 : 48));
        row.AddChild(new Label
        {
            Text = GetMarkingName(entry.Prototype),
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactText,
            VerticalAlignment = VAlignment.Center,
            HorizontalExpand = true,
            ClipText = true,
        });

        var remove = new Button
        {
            Text = "X",
            MinWidth = 40,
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactButton,
            VerticalAlignment = VAlignment.Center,
        };
        remove.OnPressed += _ => _markingsModel?.TryDeselectMarking(entry.Organ, entry.Layer, entry.Prototype.ID);
        row.AddChild(remove);

        return panel;
    }

    private IEnumerable<MarkingEntry> GetAvailableEntries()
    {
        if (_markingsModel is null)
            yield break;

        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            if (!_markingsModel.OrganProfileData.TryGetValue(organ, out var organProfileData))
                continue;

            foreach (var layer in organData.Layers)
            {
                if (!CurrentZone.Layers.Contains(layer))
                    continue;

                var markings = _markingsModel.EnforceGroupAndSexRestrictions
                    ? _marking.MarkingsByLayerAndSpeciesGroupAndSex(layer, _markingsModel.Species, organData.Group, organProfileData.Sex)
                    : _marking.MarkingsByLayer(layer);

                foreach (var marking in markings.Values)
                {
                    yield return new MarkingEntry(organ, layer, marking);
                }
            }
        }
    }

    private IEnumerable<MarkingEntry> GetSelectedEntries()
    {
        if (_markingsModel is null)
            yield break;

        foreach (var (organ, organMarkings) in _markingsModel.Markings)
        {
            foreach (var (layer, markings) in organMarkings)
            {
                if (!CurrentZone.Layers.Contains(layer))
                    continue;

                foreach (var marking in markings)
                {
                    if (_prototype.TryIndex<MarkingPrototype>(marking.MarkingId, out var markingProto))
                        yield return new MarkingEntry(organ, layer, markingProto);
                }
            }
        }
    }

    private void ClearSelectedZone()
    {
        if (_markingsModel is null)
            return;

        foreach (var entry in GetSelectedEntries().ToList())
        {
            _markingsModel.TryDeselectMarking(entry.Organ, entry.Layer, entry.Prototype.ID);
        }
    }

    private bool MatchesSearch(MarkingPrototype prototype, string query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return true;

        return GetMarkingName(prototype).Contains(query, StringComparison.OrdinalIgnoreCase) ||
               prototype.ID.Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    private bool MatchesFilter(MarkingEntry entry)
    {
        return _selectedFilter switch
        {
            MarkingFilter.All => true,
            MarkingFilter.Scars => IsScar(entry.Prototype),
            MarkingFilter.Bandages => IsBandage(entry.Prototype),
            MarkingFilter.Special => !IsScar(entry.Prototype) && !IsBandage(entry.Prototype),
            MarkingFilter.Face => entry.Layer is HumanoidVisualLayers.Snout or HumanoidVisualLayers.SnoutCover,
            MarkingFilter.Eyes => entry.Layer == HumanoidVisualLayers.Eyes,
            MarkingFilter.UpperEars => (entry.Layer is HumanoidVisualLayers.HeadTop or HumanoidVisualLayers.HeadSide) && IsEar(entry.Prototype),
            MarkingFilter.LowerEars => entry.Layer == HumanoidVisualLayers.HeadSide && IsEar(entry.Prototype),
            MarkingFilter.Horns => IsHorn(entry.Prototype),
            _ => true,
        };
    }

    private bool IsHeadOnlyFilter(MarkingFilter filter)
    {
        return filter switch
        {
            MarkingFilter.Face or MarkingFilter.Eyes or MarkingFilter.UpperEars or MarkingFilter.LowerEars or MarkingFilter.Horns => true,
            _ => false,
        };
    }

    private string GetFilterLabel(MarkingPrototype prototype)
    {
        if (IsScar(prototype))
            return "Шрамы";
        if (IsBandage(prototype))
            return "Повязки";
        return "Особые";
    }

    private bool IsScar(MarkingPrototype prototype)
    {
        var name = GetMarkingName(prototype);
        return prototype.ID.Contains("Scar", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("шрам", StringComparison.OrdinalIgnoreCase);
    }

    private bool IsBandage(MarkingPrototype prototype)
    {
        var name = GetMarkingName(prototype);
        return prototype.ID.Contains("Gauze", StringComparison.OrdinalIgnoreCase) ||
               prototype.ID.Contains("Bandage", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("бинт", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("повяз", StringComparison.OrdinalIgnoreCase);
    }

    private bool IsEar(MarkingPrototype prototype)
    {
        var name = GetMarkingName(prototype);
        return prototype.ID.Contains("Ear", StringComparison.OrdinalIgnoreCase) ||
               prototype.ID.Contains("Bunny", StringComparison.OrdinalIgnoreCase) ||
               prototype.ID.Contains("Rabbit", StringComparison.OrdinalIgnoreCase) ||
               prototype.ID.Contains("Hare", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("ух", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("ear", StringComparison.OrdinalIgnoreCase);
    }

    private bool IsHorn(MarkingPrototype prototype)
    {
        var name = GetMarkingName(prototype);
        return prototype.ID.Contains("Horn", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("рог", StringComparison.OrdinalIgnoreCase) ||
               name.Contains("horn", StringComparison.OrdinalIgnoreCase);
    }

    private string GetMarkingName(MarkingPrototype prototype)
    {
        return Loc.TryGetString($"marking-{prototype.ID}", out var name)
            ? name
            : prototype.ID;
    }

    private string GetLayerName(HumanoidVisualLayers layer)
    {
        return Loc.TryGetString($"markings-layer-{layer}", out var name)
            ? name
            : layer.ToString();
    }

    private IEnumerable<string> GetSpeciesTags(MarkingPrototype prototype)
    {
        if (prototype.SpeciesRestriction is null)
            yield break;

        foreach (var species in prototype.SpeciesRestriction)
        {
            if (_prototype.TryIndex<SpeciesPrototype>(species, out var speciesPrototype))
                yield return Loc.GetString(speciesPrototype.Name);
            else
                yield return species.Id;
        }
    }

    private LayeredTextureRect CreatePreview(MarkingPrototype prototype, int size = 64)
    {
        return new LayeredTextureRect
        {
            Textures = prototype.Sprites.Select(layer => _sprite.Frame0(layer)).ToList(),
            TextureScale = new Vector2(2f, 2f),
            SetSize = new Vector2(size, size),
            VerticalAlignment = VAlignment.Center,
        };
    }

    private Label CreateHeader(string text)
    {
        return new Label
        {
            Text = text.ToUpperInvariant(),
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactHeaderGold,
        };
    }

    private Label CreateEmptyLabel(string text)
    {
        return new Label
        {
            Text = text,
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactSubtle,
            Margin = new Thickness(4),
        };
    }

    private PanelContainer CreatePanel(float? width)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = width is null,
            VerticalExpand = true,
            PanelOverride = BorderedPanel(PanelColor, BorderColor),
        };

        if (width is { } setWidth)
            panel.SetWidth = setWidth;

        return panel;
    }

    private PanelContainer CreateCard(bool selected)
    {
        return new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = BorderedPanel(selected ? CardSelectedColor : CardColor, selected ? AccentColor : BorderColor),
        };
    }

    private Label CreateTag(string text)
    {
        return new Label
        {
            Text = text,
            StyleIdentifier = MainMenuControl.StyleIdentifierCompactSubtle,
            Modulate = MutedTextColor,
        };
    }

    private Control CreateDivider()
    {
        return new PanelContainer
        {
            MinHeight = 1,
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat(BorderColor),
        };
    }

    private StyleBoxFlat BorderedPanel(Color background, Color border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1),
        };
    }

    private ZoneDefinition CurrentZone => Zones.First(zone => zone.Zone == _selectedZone);

    private readonly record struct ZoneDefinition(BodyZone Zone, string Label, string Icon, HumanoidVisualLayers[] Layers);
    private readonly record struct FilterDefinition(MarkingFilter Filter, string Label);
    private readonly record struct MarkingEntry(ProtoId<OrganCategoryPrototype> Organ, HumanoidVisualLayers Layer, MarkingPrototype Prototype);

    private enum BodyZone : byte
    {
        Head,
        Hair,
        Torso,
        Tail,
        Arms,
        Legs,
        Feet,
    }

    private enum MarkingFilter : byte
    {
        All,
        Scars,
        Bandages,
        Special,
        Face,
        Eyes,
        UpperEars,
        LowerEars,
        Horns,
    }
}
