using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Construction.UI;

/// <summary>
/// Passive view for the construction/crafting window. Controlled by <see cref="ConstructionMenuPresenter"/>.
/// </summary>
public interface IConstructionMenuView : IDisposable
{
    ConstructionMenuTab ActiveTab { get; set; }

    bool ShowAvailableOnly { get; }
    bool EraseButtonPressed { get; set; }
    bool BuildButtonPressed { get; set; }
    int Quantity { get; set; }

    ItemList RecipeStepList { get; }

    event EventHandler? TabChanged;
    event EventHandler<(string search, string category)>? PopulateRecipes;
    event EventHandler<ConstructionMenu.RecipeSelectionData?>? RecipeSelected;
    event EventHandler<string>? CategorySelected;
    event EventHandler? RecipeFavorited;
    event EventHandler<bool>? BuildButtonToggled;
    event EventHandler<bool>? EraseButtonToggled;
    event EventHandler? ClearAllGhosts;
    event EventHandler? CraftRequested;

    void SetMode(ConstructionMenuMode mode);
    void SetFavoritesPanelVisible(bool visible);
    void SetCategories(IReadOnlyList<ConstructionMenu.CategoryEntry> categories);
    void SetRecipeListHeader(int count);
    void PopulateRecipeList(IReadOnlyList<ConstructionMenu.RecipeRowData> recipes);
    void PopulateFavorites(IReadOnlyList<ConstructionMenu.ConstructionMenuListData> favorites);

    void ClearRecipeInfo();
    void SetRecipeInfo(string name, string description, EntityPrototype? targetPrototype, bool isStructure, bool isFavorite);
    void SetTargetStats(string text);
    void ResetPlacement();

    event Action? OnClose;
    bool IsOpen { get; }
    void OpenCentered();
    void MoveToFront();
    bool IsAtFront();
    void Close();
}

public enum ConstructionMenuTab
{
    Construction,
    Craft,
}

public enum ConstructionMenuMode
{
    Full,
    CraftOnly,
}

[GenerateTypedNameReferences]
public sealed partial class ConstructionMenu : FancyWindow, IConstructionMenuView
{
    private static readonly Color AccentColor = Color.FromHex("#FFB52A");
    private static readonly Color AccentDark = Color.FromHex("#A85E12");
    private static readonly Color PanelBg = Color.FromHex("#1A0900");
    private static readonly Color SelectedBorder = Color.FromHex("#FFB52A");
    private static readonly Color AvailableGreen = Color.FromHex("#31843E");
    private static readonly Color UnavailableRed = Color.FromHex("#BB3232");

    private readonly ButtonGroup _tabGroup = new();
    private readonly Dictionary<string, ContainerButton> _categoryButtons = new();
    private readonly Dictionary<string, ContainerButton> _recipeButtons = new();
    private readonly Dictionary<string, PanelContainer> _recipePanels = new();
    private string _selectedCategory = string.Empty;
    private string? _selectedRecipeId;
    private ConstructionMenuMode _mode = ConstructionMenuMode.Full;

    public void SetMode(ConstructionMenuMode mode)
    {
        _mode = mode;
        TabBar.Visible = mode == ConstructionMenuMode.Full;

        if (mode == ConstructionMenuMode.CraftOnly)
        {
            ActiveTab = ConstructionMenuTab.Craft;
            UpdateActionPanels();
        }
    }

    public void SetFavoritesPanelVisible(bool visible)
    {
        FavoritesPanel.Visible = visible;
    }

    public ConstructionMenuTab ActiveTab
    {
        get => _mode == ConstructionMenuMode.CraftOnly || CraftTabButton.Pressed
            ? ConstructionMenuTab.Craft
            : ConstructionMenuTab.Construction;
        set
        {
            ConstructionTabButton.Pressed = value == ConstructionMenuTab.Construction;
            CraftTabButton.Pressed = value == ConstructionMenuTab.Craft;
            UpdateTabVisuals();
            UpdateActionPanels();
        }
    }

    public bool ShowAvailableOnly => ShowAvailableOnlyCheck.Pressed;

    public bool BuildButtonPressed
    {
        get => BuildButton.Pressed;
        set => BuildButton.Pressed = value;
    }

    public bool EraseButtonPressed
    {
        get => EraseButton.Pressed;
        set => EraseButton.Pressed = value;
    }

    public int Quantity
    {
        get => int.TryParse(QuantityInput.Text, out var q) && q > 0 ? q : 1;
        set => QuantityInput.Text = Math.Max(1, value).ToString();
    }

    public ConstructionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("construction-menu-title");
        ConstructionTabButton.Group = _tabGroup;
        CraftTabButton.Group = _tabGroup;

        StyleTabButton(ConstructionTabButton, true);
        StyleTabButton(CraftTabButton, false);

        ConstructionTabButton.OnToggled += _ => OnTabSwitched();
        CraftTabButton.OnToggled += _ => OnTabSwitched();

        SearchBar.OnTextChanged += _ => RequestPopulate();
        ShowAvailableOnlyCheck.OnToggled += _ => RequestPopulate();

        BuildButton.OnToggled += args => BuildButtonToggled?.Invoke(this, args.Pressed);
        EraseButton.OnToggled += args => EraseButtonToggled?.Invoke(this, args.Pressed);
        ClearButton.OnPressed += _ => ClearAllGhosts?.Invoke(this, EventArgs.Empty);
        FavoriteButton.OnPressed += _ => RecipeFavorited?.Invoke(this, EventArgs.Empty);
        CraftButton.OnPressed += _ => CraftRequested?.Invoke(this, EventArgs.Empty);

        QuantityMinus10.OnPressed += _ => AdjustQuantity(-10);
        QuantityMinus.OnPressed += _ => AdjustQuantity(-1);
        QuantityPlus.OnPressed += _ => AdjustQuantity(1);
        QuantityPlus10.OnPressed += _ => AdjustQuantity(10);

        UpdateActionPanels();
    }

    public event EventHandler? TabChanged;
    public event EventHandler<(string search, string category)>? PopulateRecipes;
    public event EventHandler<RecipeSelectionData?>? RecipeSelected;
    public event EventHandler<string>? CategorySelected;
    public event EventHandler? RecipeFavorited;
    public event EventHandler<bool>? BuildButtonToggled;
    public event EventHandler<bool>? EraseButtonToggled;
    public event EventHandler? ClearAllGhosts;
    public event EventHandler? CraftRequested;

    public void SetCategories(IReadOnlyList<CategoryEntry> categories)
    {
        CategoryList.RemoveAllChildren();
        _categoryButtons.Clear();

        foreach (var entry in categories)
        {
            var button = new ContainerButton
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = entry.Selected,
                MinHeight = 30,
            };

            var label = new Label
            {
                Text = $"{entry.Name}  {entry.Count}",
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(4, 0),
            };
            button.AddChild(label);

            StyleCategoryButton(button, entry.Selected);
            var catId = entry.Id;
            button.OnToggled += _ =>
            {
                foreach (var (id, btn) in _categoryButtons)
                    StyleCategoryButton(btn, id == catId && button.Pressed);

                if (button.Pressed)
                {
                    _selectedCategory = catId;
                    CategorySelected?.Invoke(this, catId);
                    RequestPopulate();
                }
            };

            CategoryList.AddChild(button);
            _categoryButtons[entry.Id] = button;
        }
    }

    public void SetRecipeListHeader(int count)
    {
        RecipeListHeader.Text = Loc.GetString("construction-menu-recipes-header-count", ("count", count));
    }

    public void PopulateRecipeList(IReadOnlyList<RecipeRowData> recipes)
    {
        RecipeList.RemoveAllChildren();
        _recipeButtons.Clear();
        _recipePanels.Clear();

        foreach (var row in recipes)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                MinHeight = 44,
            };
            StyleRecipePanel(panel, row.Id == _selectedRecipeId);

            var button = new ContainerButton
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = row.Id == _selectedRecipeId,
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(6, 4),
                SeparationOverride = 8,
            };

            var icon = new EntityPrototypeView
            {
                SetSize = new Vector2(32, 32),
                Stretch = SpriteView.StretchMode.Fill,
            };
            icon.SetPrototype(row.TargetPrototype);
            content.AddChild(icon);

            var textCol = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 2,
            };

            var nameLabel = new Label
            {
                Text = row.Name,
                ClipText = true,
            };
            textCol.AddChild(nameLabel);

            var statusLabel = new Label
            {
                Text = row.Available
                    ? Loc.GetString("construction-menu-status-available")
                    : Loc.GetString("construction-menu-status-unavailable"),
                Modulate = row.Available ? AvailableGreen : UnavailableRed,
                StyleClasses = { StyleNano.StyleClassLabelSmall },
            };
            textCol.AddChild(statusLabel);
            content.AddChild(textCol);

            if (row.IsFavorite)
            {
                var star = new Label
                {
                    Text = "★",
                    Modulate = AccentColor,
                    VerticalAlignment = Control.VAlignment.Center,
                };
                content.AddChild(star);
            }

            button.AddChild(content);
            panel.AddChild(button);
            RecipeList.AddChild(panel);

            var data = new RecipeSelectionData(row.Id, row.TargetPrototype);
            var protoId = row.Id;
            button.OnToggled += args =>
            {
                if (args.Pressed)
                {
                    _selectedRecipeId = protoId;
                    foreach (var (id, p) in _recipePanels)
                        StyleRecipePanel(p, id == protoId);
                    RecipeSelected?.Invoke(this, data);
                }
                else if (_selectedRecipeId == protoId)
                {
                    _selectedRecipeId = null;
                    StyleRecipePanel(panel, false);
                    RecipeSelected?.Invoke(this, null);
                }
            };

            _recipeButtons[protoId] = button;
            _recipePanels[protoId] = panel;
        }
    }

    public void PopulateFavorites(IReadOnlyList<ConstructionMenuListData> favorites)
    {
        FavoritesBar.RemoveAllChildren();

        foreach (var fav in favorites)
        {
            var slot = new ContainerButton
            {
                MinSize = new Vector2(52, 52),
                MaxSize = new Vector2(52, 52),
                ToolTip = fav.Prototype.Name,
            };

            var panel = new PanelContainer();
            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PanelBg,
                BorderColor = Color.FromHex("#A85E1266"),
                BorderThickness = new Thickness(1),
            };

            var icon = new EntityPrototypeView
            {
                SetSize = new Vector2(40, 40),
                Stretch = SpriteView.StretchMode.Fill,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };
            icon.SetPrototype(fav.TargetPrototype);

            panel.AddChild(icon);
            slot.AddChild(panel);

            var data = fav;
            slot.OnPressed += _ => RecipeSelected?.Invoke(this, new RecipeSelectionData(fav.Prototype.ID, fav.TargetPrototype));
            FavoritesBar.AddChild(slot);
        }
    }

    public void SetTargetStats(string text)
    {
        TargetStats.Text = text;
    }

    public void ClearRecipeInfo()
    {
        BuildButton.Disabled = true;
        CraftButton.Disabled = true;
        TargetName.Text = string.Empty;
        TargetDesc.SetMessage(string.Empty);
        TargetStats.Text = string.Empty;
        TargetTexture.SetPrototype(null);
        FavoriteButton.Visible = false;
        RecipeStepList.Clear();
    }

    public void SetRecipeInfo(
        string name,
        string description,
        EntityPrototype? targetPrototype,
        bool isStructure,
        bool isFavorite)
    {
        BuildButton.Disabled = false;
        CraftButton.Disabled = false;
        TargetName.Text = name.ToUpperInvariant();
        TargetDesc.SetMessage(description);
        TargetTexture.SetPrototype(targetPrototype?.ID);
        FavoriteButton.Visible = true;
        FavoriteButton.Text = Loc.GetString(
            isFavorite ? "construction-add-favorite-button" : "construction-remove-from-favorite-button");

        BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
        CraftButton.Text = Loc.GetString("construction-menu-create");
    }

    public void ResetPlacement()
    {
        BuildButton.Pressed = false;
        EraseButton.Pressed = false;
    }

    private void OnTabSwitched()
    {
        if (_mode == ConstructionMenuMode.CraftOnly)
            return;

        UpdateTabVisuals();
        UpdateActionPanels();
        SearchBar.SetText(string.Empty);
        _selectedRecipeId = null;
        TabChanged?.Invoke(this, EventArgs.Empty);
        RequestPopulate();
    }

    private void UpdateTabVisuals()
    {
        StyleTabButton(ConstructionTabButton, ConstructionTabButton.Pressed);
        StyleTabButton(CraftTabButton, CraftTabButton.Pressed);
    }

    private void UpdateActionPanels()
    {
        var isConstruction = ActiveTab == ConstructionMenuTab.Construction;
        ConstructionActions.Visible = isConstruction;
        CraftActions.Visible = !isConstruction;
        IngredientsHeader.Text = Loc.GetString(isConstruction
            ? "construction-menu-steps-header"
            : "construction-menu-ingredients-header");
    }

    private void RequestPopulate()
    {
        PopulateRecipes?.Invoke(this, (SearchBar.Text, _selectedCategory));
    }

    private void AdjustQuantity(int delta)
    {
        Quantity = Math.Max(1, Quantity + delta);
    }

    private static void StyleTabButton(ContainerButton button, bool active)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = active ? AccentColor : PanelBg,
            BorderColor = active ? AccentDark : Color.FromHex("#A85E124D"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 12,
            ContentMarginRightOverride = 12,
        };
        if (button.Children.FirstOrDefault() is Label label)
            label.Modulate = active ? Color.Black : AccentColor;
    }

    private static void StyleCategoryButton(ContainerButton button, bool selected)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = selected ? Color.FromHex("#2A1200") : Color.Transparent,
            BorderColor = selected ? SelectedBorder : Color.Transparent,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
        };
        if (button.Children.FirstOrDefault() is Label label)
            label.Modulate = selected ? AccentColor : Color.FromHex("#A6A6A6");
    }

    private static void StyleRecipePanel(PanelContainer panel, bool selected)
    {
        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = selected ? Color.FromHex("#2A1200") : Color.FromHex("#0A0400"),
            BorderColor = selected ? SelectedBorder : Color.FromHex("#A85E1233"),
            BorderThickness = new Thickness(1),
        };
    }

    public sealed record ConstructionMenuListData(ConstructionPrototype Prototype, EntityPrototype TargetPrototype) : ListData;

    public sealed record RecipeSelectionData(string Id, EntityPrototype TargetPrototype);

    public readonly record struct CategoryEntry(string Id, string Name, int Count, bool Selected);

    public readonly record struct RecipeRowData(
        string Id,
        string Name,
        EntityPrototype TargetPrototype,
        bool Available,
        bool IsFavorite);
}
