using System;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    /// <summary>
    /// Height taken by everything around the sprite viewport: the header, the name/age lines,
    /// the personalisation button, and the separations and margins between them.
    /// </summary>
    private const float ChromeHeight = 130f;

    private const float ViewportNaturalHeight = 132f;

    /// <summary>
    /// Below this the viewport is dropped entirely, so the name and the personalisation button
    /// keep their space instead of being squeezed out of the panel.
    /// </summary>
    private const float ViewportMinHeight = 48f;

    public Button CharacterSetupButton => CharacterSetup;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Fits the panel's contents into <paramref name="height"/> by shrinking, and eventually dropping,
    /// the sprite viewport. The panel itself never lays out below <see cref="ChromeHeight"/>.
    /// </summary>
    public void ApplyHeight(float height)
    {
        var viewportHeight = MathF.Min(height - ChromeHeight, ViewportNaturalHeight);
        var showViewport = viewportHeight >= ViewportMinHeight;

        PreviewViewport.Visible = showViewport;
        PreviewViewport.ReservesSpace = showViewport;

        if (!showViewport)
            return;

        PreviewViewport.SetHeight = viewportHeight;
        ProfilePreviewSpriteView.MaxHeight = viewportHeight - 4f;
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        CharacterName.Text = value;
        CharacterAge.Text = string.Empty;
    }

    public void SetCharacterInfo(string name, int age)
    {
        CharacterName.Text = name;
        CharacterAge.Text = $"{age} \u043B\u0435\u0442";
    }
}
