using System.Linq;
using System.Numerics;
using Content.Shared.Atmos;
using Content.Shared._Eclipse.AdvancedHealth;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            NoPatientDataText.Visible = true;
            return;
        }

        NoPatientDataText.Visible = false;

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value,
                out var humanoidComponent)
                ? Loc.GetString(_prototypes.Index(humanoidComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent)
                ? GetStatus(mobStateComponent.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // Total Damage

        DamageLabel.Text = _damageable.GetTotalDamage(target.Value).ToString();

        // Optional advanced physiology. Legacy patients never show this panel.
        var advanced = state.AdvancedBodyParts != null;
        AdvancedHealthContainer.Visible = advanced;
        AdvancedHealthDivider.Visible = advanced;
        if (advanced)
        {
            AdvancedBodyDoll.SetState(state.AdvancedBodyParts);
            AdvancedBloodLabel.Text = Loc.GetString("advanced-health-scanner-blood",
                ("value", (state.AdvancedBloodVolume ?? 0) * 100));
            if (state.AdvancedBodyFluid != null && state.AdvancedBloodType != null)
            {
                var carry = (int) MathF.Round(Math.Clamp(state.AdvancedOxygenCarryingCapacity ?? 1f, 0f, 1f) * 100f);
                AdvancedBloodLabel.ToolTip = Loc.GetString("advanced-health-blood-group-tooltip",
                    ("group", BloodCompatibility.Format(state.AdvancedBodyFluid, state.AdvancedBloodType)),
                    ("carry", carry));
                if (state.AdvancedFluidColor is { } fluidColor)
                    AdvancedBloodLabel.FontColorOverride = fluidColor;
            }
            AdvancedOxygenLabel.Text = Loc.GetString("advanced-health-scanner-oxygen",
                ("value", state.Oxygenation ?? 0));
            AdvancedPainLabel.Text = Loc.GetString("advanced-health-scanner-pain",
                ("value", state.Pain ?? 0));
            AdvancedShockLabel.Text = Loc.GetString("advanced-health-scanner-shock",
                ("value", state.Shock ?? 0));
            AdvancedTraumaLabel.Text = Loc.GetString("advanced-health-scanner-trauma",
                ("value", state.TraumaLoad ?? 0));
            var bleedingPart = state.AdvancedBodyParts?
                .Where(x => x.Bleeding != BleedingLevel.None)
                .OrderByDescending(x => x.Severity)
                .Select(x => Loc.GetString($"advanced-health-part-{x.Slot.ToString().ToLowerInvariant()}"))
                .FirstOrDefault();
            AdvancedBleedingLabel.Text = bleedingPart == null
                ? Loc.GetString("advanced-health-scanner-no-bleeding")
                : Loc.GetString("advanced-health-scanner-bleeding", ("part", bleedingPart));
        }

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        // Damage Groups

        var damageSortedGroups =
            _damageable.GetDamagePerGroup(target.Value)
                .OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);

        var damagePerType = _damageable.GetAllDamage(target.Value).DamageDict;

        DrawDiagnosticGroups(damageSortedGroups, damagePerType);
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (damageAmount == 0)
                continue;

            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            var groupContainer = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));

            GroupsContainer.AddChild(groupContainer);

            // Show the damage for each type in that group.
            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount)
                );

                groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower())
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }
}
