using System;
using System.Numerics;
using System.Threading;
using Robust.Client.AutoGenerated;
using Robust.Client.Eclipse;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Eclipse.Engine.UI;

[GenerateTypedNameReferences]
public sealed partial class EclipseEngineDownloadDialog : DefaultWindow
{
    private CancellationTokenSource? _cancelSource;

    public EclipseEngineDownloadDialog()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("eclipse-engine-download-window-title");
        MinSize = new Vector2(460, 260);
        Resizable = false;

        CancelButton.OnPressed += _ => Cancel();
        OnClose += Cancel;
    }

    public CancellationToken BeginOperation()
    {
        _cancelSource = new CancellationTokenSource();
        CancelButton.Disabled = false;
        return _cancelSource.Token;
    }

    public void UpdateProgress(EclipseEngineDownloadStatus status)
    {
        PhaseLabel.Text = status.Phase switch
        {
            "Downloading engine" => Loc.GetString("eclipse-engine-download-phase-downloading"),
            "Extracting engine" => Loc.GetString("eclipse-engine-download-phase-extracting"),
            "Ready" => Loc.GetString("eclipse-engine-download-phase-ready"),
            _ => status.Phase,
        };

        if (status.Phase == "Extracting engine" && status.TotalBytes is > 0)
        {
            DownloadProgress.Value = status.DownloadedBytes / (float) status.TotalBytes.Value;
            BytesLabel.Text = Loc.GetString(
                "eclipse-engine-download-extract-progress",
                ("current", status.DownloadedBytes),
                ("total", status.TotalBytes.Value));
            SpeedLabel.Text = string.Empty;
            EtaLabel.Text = string.Empty;
            return;
        }

        if (status.TotalBytes is > 0)
        {
            DownloadProgress.Value = status.DownloadedBytes / (float) status.TotalBytes.Value;
            BytesLabel.Text = Loc.GetString(
                "eclipse-engine-download-bytes",
                ("downloaded", FormatBytes(status.DownloadedBytes)),
                ("total", FormatBytes(status.TotalBytes.Value)));
        }
        else
        {
            DownloadProgress.Value = Math.Clamp(status.DownloadedBytes / (50f * 1024 * 1024), 0f, 0.95f);
            BytesLabel.Text = Loc.GetString(
                "eclipse-engine-download-bytes-unknown",
                ("downloaded", FormatBytes(status.DownloadedBytes)));
        }

        SpeedLabel.Text = status.BytesPerSecond > 1
            ? Loc.GetString("eclipse-engine-download-speed", ("speed", FormatBytes((long) status.BytesPerSecond) + "/s"))
            : string.Empty;

        EtaLabel.Text = status.EstimatedTimeRemaining is { } eta
            ? Loc.GetString("eclipse-engine-download-eta", ("eta", FormatTime(eta)))
            : string.Empty;
    }

    public void Cancel()
    {
        _cancelSource?.Cancel();
        CancelButton.Disabled = true;
    }

    private static string FormatBytes(long bytes)
    {
        if (bytes < 1024)
            return $"{bytes} B";

        if (bytes < 1024 * 1024)
            return $"{bytes / 1024f:0.0} KiB";

        return $"{bytes / (1024f * 1024f):0.0} MiB";
    }

    private static string FormatTime(TimeSpan eta)
    {
        if (eta.TotalHours >= 1)
            return $"{(int) eta.TotalHours}:{eta.Minutes:D2}:{eta.Seconds:D2}";

        if (eta.TotalMinutes >= 1)
            return $"{eta.Minutes}:{eta.Seconds:D2}";

        return $"{Math.Max(1, (int) eta.TotalSeconds)}s";
    }
}
